version: "3.7"

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    networks:
      rede:
        ipv4_address: 10.5.0.5
volumes:
  postgres-data:
networks:
  rede:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1